import inquirer from 'inquirer';
import fs from 'fs-extra';
import path from 'path';
import { Listr } from 'listr2';
import { z } from 'zod';
import { logger } from '../utils/logger.js';
import { Engine } from '../utils/engine.js';

const ProjectSchema = z.object({
  projectName: z.string().min(1).regex(/^[a-z0-9-]+$/),
  projectType: z.enum(['node-esm', 'express-ts', 'react-vite', 'static', 'cli-tool']),
  features: z.array(z.string()),
  gitInit: z.boolean()
});

export const initCommand = async () => {
  logger.info('INITIALIZING ADVANCED PROJECT SCAFFOLDING');

  const answers = await inquirer.prompt([
    {
      type: 'input',
      name: 'projectName',
      message: 'FAHH-cli: PROJECT IDENTIFIER (slug):',
      default: 'fahh-service'
    },
    {
      type: 'list',
      name: 'projectType',
      message: 'FAHH-cli: ARCHITECTURE TEMPLATE:',
      choices: [
        { name: 'NODE.JS (ESM)', value: 'node-esm' },
        { name: 'EXPRESS API (TS)', value: 'express-ts' },
        { name: 'REACT (VITE)', value: 'react-vite' },
        { name: 'STATIC SITE', value: 'static' },
        { name: 'CLI TOOL', value: 'cli-tool' }
      ]
    },
    {
      type: 'checkbox',
      name: 'features',
      message: 'FAHH-cli: SELECT OPTIONAL FEATURES:',
      choices: [
        { name: 'ESLint + Prettier', value: 'linting', checked: true },
        { name: 'Unit Testing (Vitest/Node)', value: 'testing', checked: true },
        { name: 'GitHub Actions (CI)', value: 'ci' },
        { name: 'Docker Support', value: 'docker' }
      ]
    },
    {
      type: 'confirm',
      name: 'gitInit',
      message: 'FAHH-cli: INITIALIZE SOURCE CONTROL?',
      default: true
    }
  ]);

  // Production-grade validation
  const validation = ProjectSchema.safeParse(answers);
  if (!validation.success) {
    logger.error(`VALIDATION FAILED: ${JSON.stringify(validation.error.format())}`);
    return;
  }

  const { projectName, projectType, gitInit, features } = validation.data;
  const projectDir = path.resolve(process.cwd(), projectName);

  if (fs.existsSync(projectDir)) {
    logger.error(`NAMESPACE CONFLICT: DIRECTORY ${projectName} ALREADY EXISTS`);
    return;
  }

  const tasks = new Listr([
    {
      title: 'FAHH-cli: CONSTRUCTING FILE SYSTEM',
      task: async () => {
        await fs.ensureDir(projectDir);
        await fs.ensureDir(path.join(projectDir, 'src'));
        if (features.includes('testing')) {
          await fs.ensureDir(path.join(projectDir, 'tests'));
        }
        if (projectType === 'express-ts') {
          await fs.ensureDir(path.join(projectDir, 'src/routes'));
          await fs.ensureDir(path.join(projectDir, 'src/middleware'));
        }
      }
    },
    {
      title: 'FAHH-cli: APPLYING TEMPLATE MANIFESTS',
      task: async () => {
        const pkg = {
          name: projectName,
          version: '0.1.0',
          private: true,
          scripts: {}
        };

        if (projectType === 'node-esm' || projectType === 'cli-tool') {
          pkg.type = 'module';
          pkg.scripts.start = 'node src/index.js';
          if (features.includes('testing')) {
            pkg.scripts.test = 'node --test tests/*.test.js';
          }
          await fs.writeFile(path.join(projectDir, 'src/index.js'), 'console.log(\'FAHH RUNTIME ACTIVE\');\n');
        }

        if (projectType === 'express-ts') {
          pkg.scripts.dev = 'tsx watch src/index.ts';
          pkg.scripts.build = 'tsc';
          pkg.devDependencies = {
            'tsx': '^4.0.0',
            'typescript': '^5.0.0',
            '@types/node': '^20.0.0',
            '@types/express': '^4.0.0'
          };
          pkg.dependencies = {
            'express': '^4.18.0'
          };
          await fs.writeFile(path.join(projectDir, 'src/index.ts'), 'import express from \'express\';\nconst app = express();\napp.listen(3000, () => console.log(\'SERVER READY\'));\n');
        }

        await fs.writeJson(path.join(projectDir, 'package.json'), pkg, { spaces: 2 });
        await fs.writeFile(path.join(projectDir, '.gitignore'), 'node_modules\n.env\ndist\n');
        
        if (features.includes('docker')) {
          await fs.writeFile(path.join(projectDir, 'Dockerfile'), 'FROM node:20-slim\nWORKDIR /app\nCOPY package*.json ./\nRUN npm install\nCOPY . .\nCMD ["npm", "start"]\n');
        }

        if (features.includes('ci')) {
          await fs.ensureDir(path.join(projectDir, '.github/workflows'));
          await fs.writeFile(path.join(projectDir, '.github/workflows/ci.yml'), 'name: CI\non: [push]\njobs:\n  build:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n      - uses: actions/setup-node@v4\n      - run: npm install\n      - run: npm test\n');
        }

        await fs.writeFile(path.join(projectDir, 'README.md'), `# ${projectName.toUpperCase()}\n\nGENERATED BY FAHH-CLI ENGINE\n`);
      }
    },
    {
      title: 'FAHH-cli: INITIALIZING GIT REPOSITORY',
      enabled: () => gitInit,
      task: () => {
        Engine.exec('git init', { cwd: projectDir });
      }
    }
  ]);

  try {
    await tasks.run();
    logger.success(`PROJECT ${projectName.toUpperCase()} READY FOR DEVELOPMENT`);
  } catch (e) {
    logger.error(`SCAFFOLDING ENGINE ERROR: ${e.message}`);
  }
};
