import inquirer from 'inquirer';
import fs from 'fs-extra';
import path from 'path';
import { Listr } from 'listr2';
import { z } from 'zod';
import { logger } from '../utils/logger.js';
import { Engine } from '../utils/engine.js';

const ProjectSchema = z.object({
  projectName: z.string().min(1).regex(/^[a-z0-9-]+$/),
  projectType: z.enum(['node-esm', 'react-vite', 'static']),
  gitInit: z.boolean()
});

export const initCommand = async () => {
  logger.info('INITIALIZING ADVANCED PROJECT SCAFFOLDING');

  const answers = await inquirer.prompt([
    {
      type: 'input',
      name: 'projectName',
      message: 'FAHH-cli: PROJECT IDENTIFIER (slug):',
      default: 'fahh-service'
    },
    {
      type: 'list',
      name: 'projectType',
      message: 'FAHH-cli: ARCHITECTURE TEMPLATE:',
      choices: [
        { name: 'NODE.JS (ESM)', value: 'node-esm' },
        { name: 'REACT (VITE)', value: 'react-vite' },
        { name: 'STATIC SITE', value: 'static' }
      ]
    },
    {
      type: 'confirm',
      name: 'gitInit',
      message: 'FAHH-cli: INITIALIZE SOURCE CONTROL?',
      default: true
    }
  ]);

  // Production-grade validation
  const validation = ProjectSchema.safeParse(answers);
  if (!validation.success) {
    logger.error(`VALIDATION FAILED: ${JSON.stringify(validation.error.format())}`);
    return;
  }

  const { projectName, projectType, gitInit } = validation.data;
  const projectDir = path.resolve(process.cwd(), projectName);

  if (fs.existsSync(projectDir)) {
    logger.error(`NAMESPACE CONFLICT: DIRECTORY ${projectName} ALREADY EXISTS`);
    return;
  }

  const tasks = new Listr([
    {
      title: 'FAHH-cli: CONSTRUCTING FILE SYSTEM',
      task: async () => {
        await fs.ensureDir(projectDir);
        await fs.ensureDir(path.join(projectDir, 'src'));
        await fs.ensureDir(path.join(projectDir, 'tests'));
      }
    },
    {
      title: 'FAHH-cli: APPLYING TEMPLATE MANIFESTS',
      task: async () => {
        if (projectType === 'node-esm') {
          const pkg = {
            name: projectName,
            version: '0.1.0',
            type: 'module',
            private: true,
            scripts: { 
              start: 'node src/index.js',
              test: 'node --test tests/*.test.js'
            }
          };
          await fs.writeJson(path.join(projectDir, 'package.json'), pkg, { spaces: 2 });
          await fs.writeFile(path.join(projectDir, 'src/index.js'), 'export const main = () => console.log(\'FAHH RUNTIME ACTIVE\');\nmain();\n');
        }
        await fs.writeFile(path.join(projectDir, '.gitignore'), 'node_modules\n.env\ndist\n');
        await fs.writeFile(path.join(projectDir, 'README.md'), `# ${projectName.toUpperCase()}\n\nGENERATED BY FAHH-CLI ENGINE\n`);
      }
    },
    {
      title: 'FAHH-cli: INITIALIZING GIT REPOSITORY',
      enabled: () => gitInit,
      task: () => {
        Engine.exec('git init', { cwd: projectDir });
      }
    }
  ]);

  try {
    await tasks.run();
    logger.success(`PROJECT ${projectName.toUpperCase()} READY FOR DEVELOPMENT`);
  } catch (e) {
    logger.error(`SCAFFOLDING ENGINE ERROR: ${e.message}`);
  }
};
